FROM node:20.6-alpine

WORKDIR /application

COPY . .

RUN npm ci
RUN npm build
RUN npm -g i serve

ENV PATH /application/node_modules/.bin:$PATH

CMD ["serve", "-s", "/application/build", "-l", "80"]
